### PR TITLE
Beta v4 updates

### PR DESCRIPTION
**Pull request by Amerlander**
- closes https://github.com/microsoft/pxt-calliope/issues/191
- closes https://github.com/microsoft/pxt-calliope/issues/192
- closes https://github.com/microsoft/pxt-calliope/issues/193
- closes https://github.com/microsoft/pxt-calliope/issues/194

- Adds groups in `pin` Blocks
- increase ble table size for 16M devices
- resets defaults for text scroll speed and icon display time
- adds button A & B up and down events when `A+B Button` is pressed in simulator
- adds button & pin pressed/clicked/released blocks as deprecated to get translations back in current makecode version
- set `partial_flashing: 1`

### CODE REVIEW

**Comment by Amerlander** [comment]
@riknoll can you merge this again and create a release? Thank you! :)

**Comment by joernalraun** [comment]
Bump... 😉

**Comment by riknoll** [comment]
ah, sorry! I was off for a few days

**Review by riknoll — APPROVED** [review]
Code LGTM!

@abchatra can you approve the two extensions that have been added to the target config?

**Comment by abchatra** [comment]
I looked at the extensions and they look good. In future please open separate PR for the extensions and tag me. Thank you!

**Comment by riknoll** [comment]
@Amerlander @joernalraun bumped! sorry for the delay!

**Pull request merged**
