### PR TITLE
V4 updates for beta testing

### PR DESCRIPTION
**Pull request by Amerlander**
A static hosted version of these changes can be seen at [betamc.calliope.cc](https://betamc.calliope.cc/)

### CODE REVIEW

**Comment by Amerlander** [comment]
The checks here are failing by certificate errors:

```
polling C++ build https://makecode.com/compile/b13e67d2388406bad428d0e45afee8dd75d2809c4499b80fba4ff55d7f70a224.json (attempt #1)
build log https://makecode.com/compile/b13e67d2388406bad428d0e45afee8dd75d2809c4499b80fba4ff55d7f70a224.log
build failed
info: get versions for calliope-mini-classic-gcc
warning: connection error: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],), retrying...
warning: connection error: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],), retrying...
warning: connection error: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],), retrying...
warning: connection error: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],), retrying...
error: connection error: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
Fatal Exception, yotta=0.14.1
```

**Comment by abchatra** [comment]
@Amerlander many of the following extensions don't have MIT license. We need MIT license to serve these extensions. Can you please add MIT license or remove them from the targetconfig? 


            "calliope-edu/pxt-sunlightsensor-si1145",
            "calliope-edu/pxt-rgblcd",
            "calliope-mini/pxt-SCD30",
            "calliope-edu/CO2-Sensor-SCD40",
            "calliope-edu/pxt-temperatursensor",
            "calliope-edu/pxt-display",
            "calliope-edu/pxt-HM3301_Dust_Sensor",
            "MKleinSB/pxt-callimotor",
            "MKleinSB/pxt-kitronik-zip-tile-calliope",
            "MKleinSB/pxt-MAX7219_8x8",

**Comment by Amerlander** [comment]
@abchatra of course! I'll check tomorrow where we can add the MIT license, update these and remove the others.

**Comment by Amerlander** [comment]
@abchatra we updated or removed all extensions inside `preferredRepos` in the `targetconfig.ts`.

**Comment by joernalraun** [comment]
> For example: https://github.com/calliope-edu/pxt-SCD30 doesn't have MIT license.
> 
> Is there any issue in adding the MIT license for them? All these repos are severed text files any way so users can use them as library.

We just didn't know that an MIT license is necessary. The license has been updated at all the extensions.
Maybe extensions without license could be automatically excluded?

**Comment by Amerlander** [comment]
@joernalraun we only updated the preffered repos, not all listed. The pxt-SCD30 has MIT, but its only mentioned inside the Readme, there is the License file missing.

I'll go through the list and add the MIT license or remove them if they have other licenses.

**Comment by Amerlander** [comment]
@abchatra I checked now every extension and removed it if there was no license file with MIT License included.

Since `pxt-calliope` is a fork of `pxt-microbit` there are several extensions you are still using in the Microbit Target.

The extension `Tinkertanker/pxt-tinkercademy-microbot` has no license at all (https://github.com/microsoft/pxt-microbit/blob/b9d2eeff8116b75fa50f663091b0e3acd800b7bc/targetconfig.json#L37).

The following extensions have a MIT License mentioned in the Readme, but wthout the full license text and no license file. So they are the same like the https://github.com/calliope-edu/pxt-SCD30 you mentioned:
```
Annikken/pxt-Andee
LaboratoryForPlayfulComputation/pxt-BlockyTalkyBLE
PaulDFoster/pxt-microbit-GY521
Tinkertanker/microDriver_SHT2x
Tinkertanker/uDriver_PCA9585
chevyng/pxt-ucl-junkrobot
mbitfun/pxt-katakana
```
I removed all of them in the calliope target, but they are still present in the microbit target.

**Comment by abchatra** [comment]
Thanks @Amerlander We do have an issue to track down these extensions authors in microbit for the license. 
https://github.com/microsoft/pxt-microbit/issues/1769

**Comment by joernalraun** [comment]
> Thanks for doing this and sorry for the inconvenience.
Hi @abchatra is there anything else we could do now to help getting the process through?

**Comment by abchatra** [comment]
This is good to go. We are checking on the build failures and will merge after that.

**Comment by Amerlander** [comment]
@riknoll If you have more questions we could also set up a video call now or the next days if you like.

**Comment by Amerlander** [comment]
@riknoll no, there isnt. I just merged it into master.

**Comment by riknoll** [comment]
@Amerlander cloud compile is updated! The build is now succeeding on master.

The build is still failing on documentation checks, though. Our CI runs through all of the TypeScript snippets in docs to make sure they compile as a check for breaking changes.

**Comment by riknoll** [comment]
You can disable docs checking by editing the pxtarget.json and adding `"ignoreDocsErrors": true` inside the appTarget object. However, these checks are usually pretty useful because they catch errors in tutorials before they are published.

If the snippets in the docs are not meant to compile, you can also ignore them on a case-by-case basis by changing the code snippet in the markdown file to use the "typescript-ignore" language. For example:

````markdown
```typescript-ignore
// code here
```
````

**Comment by Amerlander** [comment]
So it might be possible to disable these checks for having a public available beta version and enable them back again later?

The changes you just merged are a big improvement, but we still have a list of things that have to be changed for a final release. So our plan was to use this beta to get feedback from our community and improve it step by step from here until everything works as expected.
For that process, we plan to create issues and open separate PR to target each of them. That way we could also ask for help of the Microsoft team on issues where we are not sure how to solve them best. But everything starts with having a beta to have a common ground.

**Comment by riknoll** [comment]
I think that should be fine! @abchatra FYI

**Comment by Amerlander** [comment]
@riknoll I created a PR for this change: https://github.com/microsoft/pxt-calliope/pull/154

**Comment by riknoll** [comment]
@Amerlander the build is still a little broken, doesn't seem like it can update beta for some reason. I'm going to investigate, but in the meantime here is a build with the changes pushed:

https://makecode.calliope.cc/app/f3b8cb87d8c932e5673206a3808d227e36964416-1e24dc8c20

**Pull request merged**
