### PR TITLE
Update 2024 04

### PR DESCRIPTION
**Pull request by Amerlander**
**New approved Extensions:**
- [mkleinsb/pxt-callicolor-jacdac](https://github.com/mkleinsb/pxt-callicolor-jacdac)
- [mkleinsb/pxt-calliserv-jacdac](https://github.com/mkleinsb/pxt-calliserv-jacdac)
- [mkleinsb/pxt-motor-jacdac](https://github.com/mkleinsb/pxt-motor-jacdac)

**Fixes:**
- Fix direction of Motors on V3

**Other:**
- hide `radio` and add `Funk` extension to align with educational material
- update images for some extensions
- add `one-time-pairing` Extension to allow Android users to set the right settings for mini 1 and mini 2 devices
- Change strings for Project Settings to be more clear and align with educational material

### CODE REVIEW

**Comment by Amerlander** [comment]
@abchatra can you merge and bump this PR? Thank you! :)

**Comment by abchatra** [comment]
@Amerlander  these icon images need to be <100kb to easy loading in the extension page. Is it possible to reduce it?
https://github.com/MKleinSB/pxt-callicolor-jacdac/blob/master/icon.png
https://github.com/MKleinSB/pxt-calliserv-jacdac/blob/master/icon.png

**Comment by Amerlander** [comment]
@abchatra sure, I created a PR on these repos. I'm sure MKleinSB will merge them soon.

I also minified the icons in this PR a bit more.

**Comment by MKleinSB** [comment]
Just solved the size problem.

**Pull request merged**
