### PR TITLE
add v3 core

### PR DESCRIPTION
**Pull request by Amerlander**

### CODE REVIEW

**Comment by Amerlander** [comment]
This works, but when we change the githubCorePackage the cloud building is failing and claims to not find the github Package.

image

**Comment by Amerlander** [comment]
The initial PR works fine. If we change `githubCorePackage` the cloud compilation fails.
Local compilation with changed value works fine.

The error shows, that the Branch could not be found. It does not matter weather I provide a Tag or a branch in `gittag`. Its also a public repository.

@abchatra Could you help and tell what might be wrong?
Do we need a own `serviceId`?

Microbit uses another Docker Image, which is not public. Maybe we should also change our docker image, but it does not change anything regarding this issue.

Since the CodalTarget is defined seperately I am not sure what the githuBCorePackage actually is for - it might be okay to not change it to our own repo, but I am not sure about the downsides.


```
polling C++ build https://makecode.com/compile/7b2a9a4dcbe38b35f75f1d04633da7a4d38bfec875a35f426ced89826adce047.json (attempt #1)
build log https://makecode.com/compile/7b2a9a4dcbe38b35f75f1d04633da7a4d38bfec875a35f426ced89826adce047.log
build failed
Cloning into '/home/build/prjclone'...
warning: Could not find remote branch v0.2.13-calliope to clone.
fatal: Remote branch v0.2.13-calliope not found in upstream origin
Unexpected end of command stream
```

**Comment by abchatra** [comment]
@aznhassan Can you please take a look?

**Comment by joernalraun** [comment]
> @aznhassan Can you please take a look?

@aznhassan any news on this yet? We are thinking of using the link to the original samples (for the alpha test), though it would be good to know what that link is for and if it has any effect if it is not the link to ours?

**Comment by joernalraun** [comment]
> @aznhassan Can you please take a look?
> 
> @aznhassan any news on this yet? We are thinking of using the link to the original samples (for the alpha test), though it would be good to know what that link is for and if it has any effect if it is not the link to ours?

Well... I would suggest that we are testing it with the microbit samples for the alpha as it is getting urgent now. @Amerlander can you do this please? Thanks!

**Comment by Amerlander** [comment]
Created a new PR for that: https://github.com/microsoft/pxt-calliope/pull/236

I'll close this PR, but we are still interested the learn more about the error we get when changing the samples package to our repository and how using the microbit samples might affect the calliope target.

**Pull request closed without merging**
