### PR TITLE
Upgrade to v7

### PR DESCRIPTION
**Pull request by Amerlander**
This PR upstreams with MakeCode Microbit 7.0.21 and is meant to be releases as alpha for first testings.

### CODE REVIEW

**Comment by Amerlander** [comment]
@abchatra This PR introduces version 7. Can you create us a v6 branch and pin the current stable to the latest v6, so we can safely merge this PR and start working on v7?

**Comment by abchatra** [comment]
> @abchatra This PR introduces version 7. Can you create us a v6 branch and pin the current stable to the latest v6, so we can safely merge this PR and start working on v7?

I have created v6 branch. Can you elaborate on  stable pointing to the latest v6? Do you mean beta-ref.json or alpha-ref.json? I don't see a stable-ref.json

**Comment by Amerlander** [comment]
> Can you elaborate on stable pointing to the latest v6? Do you mean beta-ref.json or alpha-ref.json? I don't see a stable-ref.json

Thank you! I meant `index-ref.json` with stable, which actually does point to the latest v6 so it should be fine as it is.

**Comment by Amerlander** [comment]
@abchatra can you merge this PR and create a release tag vor v7, so we can test it in our alpha-ref (which has `"appref": "v"`)?

**Pull request merged**
