### PR TITLE
V6 beta Upgrade

### PR DESCRIPTION
**Pull request by Amerlander**
- upgrade to v6.0.17
- add rgbled blocks
- refactor motor blocks
- add codal
- add jacdac
- add board selection (WIP)
- updates for new mini versions

### CODE REVIEW

**Comment by Amerlander** [comment]
@abchatra could you please merge this pull request and release a new version for our beta testing? Preferably, as version 6.x, as this update aligns with the pxt-microbit target in that version (6.0.17).

**Comment by abchatra** [comment]
Only reviewed at high level as this is an upstream merge.

**Comment by Amerlander** [comment]
@abchatra great, thank you!

Can we get a release out of this PR, so I can pin it to beta?
The changes for alpha will follow then.

**Comment by abchatra** [comment]
Bumped.

**Comment by Amerlander** [comment]
@abchatra Since we are now on v6, the current stable cant find the galleries: `no branch v4 in https://github.com/Microsoft/pxt-calliope` (https://pxt.azureedge.net/api/md/calliopemini/calliope/firststeps?targetVersion=4.0.29&lang=de&cdn=20230906)

Can you create a v4 branch on f43f6567f02868f79d11fb455bf25a05a3ca0146 ?

**Pull request merged**
