### PR TITLE
V4 updates 4

### PR DESCRIPTION
**Pull request by Amerlander**
- Update _locales files
- Be explicit on enabled ble services in 16K-Settings

### CODE REVIEW

**Comment by Amerlander** [comment]
@abchatra can you merge this and release a new version?

The updates in the list of extensions is just a reorder, no updates there (merged PR https://github.com/microsoft/pxt-calliope/pull/196 into this PR)

**Comment by abchatra** [comment]
Sure will do. Give me a day or two.

**Comment by abchatra** [comment]
This extension MKleinSB/pxt-CO2OLED seems new? It looks good though. Let me know if that is not intentional.  I will merge the PR otherwise.

**Comment by abchatra** [comment]
Merge the PR anyway. If the extension was not intentional feel free to remove it later.

**Comment by Amerlander** [comment]
@abchatra thank you.

@riknoll can you create a new release?

**Comment by riknoll** [comment]
@Amerlander done!

**Pull request merged**
