### PR TITLE
Update default settings for mini 1 and mini 2

### PR DESCRIPTION
**Pull request by Amerlander**
This PR improves the BLE settings for the Calliope mini 1 and Calliope mini 2. 

The new file `docs/calliope/neu.md` explains how to choose the right template for a Calliope mini.

Hidden Analog and Digital Pins are added to pins.cpp to be able to update extensions for future changes.

### CODE REVIEW

**Comment by Amerlander** [comment]
@riknoll could you merge this PR and create a new release so we can test this in /beta.

This PR also includes some preparations for our upcomming upgrade to pxt 5, which is planned for end of july/first week of august.

**Comment by Amerlander** [comment]
@abchatra @pelikhan, Is there anyone available who can help with merging this PR and creating a new release? We're eager to test it in /beta. Thank you!

**Comment by abchatra** [comment]
bumped

**Comment by abchatra** [comment]
@jwunderl I remember some fix which needs to be ported here?

**Comment by jwunderl** [comment]
Should be https://github.com/microsoft/pxt/pull/9089

**Comment by jwunderl** [comment]
I ported over the crowdin retry fix so 429's shouldn't break build anymore, also had to rotate tokens for updating build but got https://makecode.calliope.cc/beta# up to date with [v4.0.34](https://makecode.calliope.cc/v4.0.34#) @Amerlander

**Pull request merged**
