### PR TITLE
V4 updates

### PR DESCRIPTION
**Pull request by Amerlander**
Some updates to fix bugs in the latest version

fixes https://github.com/microsoft/pxt-calliope/issues/205
fixes https://github.com/microsoft/pxt-calliope/issues/206
fixes https://github.com/microsoft/pxt-calliope/issues/167

### CODE REVIEW

**Comment by riknoll** [comment]
hmm seems like headless chrome is failing to start; could be a misconfiguration of the build workflow. let me see if i can fix it...

**Comment by riknoll** [comment]
if i can't fix this by EOD tomorrow, i'll disable the tests. not sure why it's failing here and not elsewhere

**Comment by riknoll** [comment]
@Amerlander alright, if you merge master into your branch it should fix the build!

**Comment by abchatra** [comment]
@Amerlander  can you please ask the authors of the following repo to add MIT license
 
https://github.com/dl1ekm/pxt-calliope-ADS1x15
https://github.com/tinysuperlab/motionkit
https://github.com/dl1ekm/pxt-calliope-PCF85063-RTC

**Pull request merged**
